### ISSUE TITLE
Sometimes the blank page when loading data for the first time

### ISSUE THREAD

**Issue by BoyStarIT** [jaredLunde/masonic#103]
Sometimes the blank page when loading data for the first time

**Screenshots**
- This my config
![image](https://user-images.githubusercontent.com/20169665/150960512-db3b3546-9ae7-4bec-8fb3-089861d96dad.png)
- This list show
![image](https://user-images.githubusercontent.com/20169665/150961276-fe52f86c-4ff8-49f5-bd3b-86ea91e3ec2e.png)

I don't know why, please help me~!
Thanks bro

**Comment by seeden** [comment]
I have same problem. It is empty until first scroll

**Comment by seeden** [comment]
It is caused by cache of usePositioner.
I fixed it with

```js
  const nextIdRef = useRef(0);
  const currentKeys = useMemo(() => {
    return items
      .map(uniqueKey)
      .join(',');
  }, [items, uniqueKey]);

  const previousItems = usePrevious(items);
  const previousKeys = usePrevious(currentKeys);

  useMemo(() => {
    if (!previousItems) {
      return;
    }

    if (!previousItems.length && !items.length) {
      return;
    }

    if (previousKeys && currentKeys && currentKeys.startsWith(previousKeys)) {
      return;
    }

    nextIdRef.current += 1;
  }, [currentKeys, previousKeys, items, previousItems]);

  const positioner = usePositioner({
     ...
  }, [nextIdRef.current]);
```

**Comment by BoyStarIT** [comment]
I tried checking many times and didn't see that error anymore
Thanks a ton bro
