### ISSUE TITLE
Grid should listen to its own width for re-render

### ISSUE THREAD

**Issue by graceoflives** [jaredLunde/masonic#115]
**Is your feature request related to a problem? Please describe.**
The grid does not update when its width changed because parent's padding/margin changed (for example, sidebar toggle).

**Describe the solution you'd like**
The grid should update properly when its width changed because of any parent's padding/margin changed.

**Describe alternatives you've considered**
Tried using ResizeObserver on containerRef.current element to listen to width change, but the grid does not update unless page is scrolled.

**Additional context**
https://codesandbox.io/s/usemasonry-example-forked-qrschc
When click the togglePadding button, the grid does not update. It only updates when the window is resized by show/hide the console.

**Comment by tanmaybhatt** [comment]
Hey @graceoflives did you manage to resolve this? Please let me know if you have any solutions.

**Comment by graceoflives** [comment]
> Hey @graceoflives did you manage to resolve this? Please let me know if you have any solutions.

I added a state to track container's width and use a useLayoutEffect with ResizeObserver to update it. then put the state to the dependency array of `useContainerPosition`

Here is the updated code: https://codesandbox.io/s/usemasonry-example-forked-ksgyjw
