### ISSUE TITLE
Max columns

### ISSUE THREAD

**Issue by The-Code-Monkey** [jaredLunde/masonic#122]
**Is your feature request related to a problem? Please describe.**
Being able to set a maximum amount of columns would be really useful as it would allow responsive designs but limit the maximum columns

**Describe the solution you'd like**
A maxColumns param that can be used when there isnt a fixed amount of columns set.

**Describe alternatives you've considered**
using a media query hook to change the columns prop to a number when passed a certain screen size but its a little hacky in my opinion.

**Additional context**
Nice work on the library really useful and better than the others out there, for implementation and usability.

**Comment by jaredLunde** [comment]
this makes sense to me
