### ISSUE TITLE
Demo is broken: ReactDOM.createRoot is not a function

### ISSUE THREAD

**Issue by coreyward** [jaredLunde/masonic#13]
It looks like the [Codepen demo](https://codesandbox.io/s/0oyxozv75v?file=/src/index.js) linked to has something amiss. 

<img width="484" alt="Screen Shot 2020-05-07 at 1 26 14 PM" src="https://user-images.githubusercontent.com/81224/81330875-5a0bad00-9066-11ea-8c2f-1a255f772e80.png">

**Comment by jaredLunde** [comment]
Dang it, they removed my concurrent mode :(

Updated w/ a regular render function

**Comment by jaredLunde** [comment]
Thanks for reporting btw! 🥇
