### ISSUE TITLE
Requires direct dependency of `@types/node` to be built

### ISSUE THREAD

**Issue by D3SOX** [jaredLunde/masonic#131]
**Describe the bug**
It works without it in development, but it requires `@types/node` to be installed for a build.

**To Reproduce**

1. Create a Vite + React project
2. Add Masonic
3. Try to build it
    ```
    node_modules/masonic/src/use-masonry.tsx:106:16 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
    ```

**Expected behavior**
It should not require that to build.

**Additional context**
Not sure if you can remove that requirement because this is the only package in my project that needs it.

**Comment by jaredLunde** [comment]
`npm i --save-dev @types/node` this is not atypical. Many libraries include/exclude things like error messages depending on your `process.env.NODE_ENV`.

**Comment by D3SOX** [comment]
Yeah, but can't this be taken care of the package as dependency?

**Comment by jaredLunde** [comment]
No, unfortunately doing so would create a lot of conflicting dependencies. [This thread highlights the issue](https://github.com/facebook/react/issues/24304). Peer dependencies are the best place for these.
