### ISSUE TITLE
Add ability to use masonry off of a container's scroll not just window

### ISSUE THREAD

**Issue by DanBullockCS** [jaredLunde/masonic#137]
**Is your feature request related to a problem? Please describe.**
Would like to add a masonry in a scrollable div on my page, but it is using the window's scrollbar

**Describe the solution you'd like**
Would like to have a prop that lets me pass an id of a div for example that I would like to scroll through

**Describe alternatives you've considered**
Not sure if this is doable with the current setup. If it is please correct me!

**Comment by DanBullockCS** [comment]
https://codesandbox.io/s/masonic-inside-of-a-scrollable-div-example-k9l6c?file=/src/index.js
I found this example I believe it addresses this issue.

**Comment by joebnb** [comment]
> https://codesandbox.io/s/masonic-inside-of-a-scrollable-div-example-k9l6c?file=/src/index.js I found this example I believe it addresses this issue.

works，from 2015
