### ISSUE TITLE
Tab navigation doesn't seem to work correctly

### ISSUE THREAD

**Issue by bigfarts** [jaredLunde/masonic#138]
**Describe the bug**
Pressing <kbd>Tab</kbd> to switch focus to the next item in the grid selects items in an order that is not left-to-right, top-to-bottom.

**To Reproduce**

1. Create a masonry grid.
2. Press <kbd>Tab</kbd> a few times and watch the focus jump around the page. The initial <kbd>Tab</kbd> press also selects the entire grid.

**Expected behavior**
Pressing <kbd>Tab</kbd> should navigate through the items left-to-right top-to-bottom. Additionally, tab should not select the grid as a whole (the grid has tabindex=0 set).

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome, but happens on all browsers
- Version: 109

**Additional context**
The DOM elements of the grid items seem to be in an arbitrary order, which does not play nicely with tab navigation.

**Comment by jaredLunde** [comment]
Appreciate your taking the time to file an issue. You're making poor assumptions here, many of which are covered in other issues. Unfortunately, I don't have time to seek them out for you.
