### ISSUE TITLE
Best practice for disabling / switching to one column and back?

### ISSUE THREAD

**Issue by riccardolardi** [jaredLunde/masonic#141]
What's the recommended way to switch to one column layout and back to original state? Should I just re-init the whole component / masonic or is there a more convenient way?

**Comment by jaredLunde** [comment]
Sorry not sure I understand the ask so this may not help, but there is a `columnCount` property you can set and under.

**Comment by riccardolardi** [comment]
@jaredLunde thanks, of course, I missed that :)
