### ISSUE TITLE
Passing ref to render item?

### ISSUE THREAD

**Issue by damiponce** [jaredLunde/masonic#149]
This is purely a question, I can't seem to find how to pass a ref to the RenderComponent. 

If I try to define my component like
```typescript
const Card = React.forwardRef(({data},ref) => {
```
and call it like
```typescript
<Masonry
  render={(e) => <Card data={e.data} ref={ref} 
  ...
/> 
```
it re-renders indefinitely when hovered.

**Comment by jaredLunde** [comment]
Anyone landing on this issue, use the same solve described here: https://github.com/jaredLunde/masonic/issues/32
