### ISSUE TITLE
ResizeObserver polyfill should be provided through a prop instead of included in the bundle

### ISSUE THREAD

**Issue by aalpgiray** [jaredLunde/masonic#151]
Hey! 

We noticed `"@juggle/resize-observer": "^3.3.1",` package is in dependencies. But depending of the target browsers that might not be needed. Can we remove this from the bundle and add this as optional peer dependency or to the documents. This will reduce the bundle size. [Here is the analysis. 
](https://bundlephobia.com/package/masonic@3.7.0)
![image](https://github.com/jaredLunde/masonic/assets/6337113/0a89b926-84a0-4dbb-aebe-1a60a757f304)

**Comment by jaredLunde** [comment]
All things considered the bundle size is not a big problem. However, I agree that in this day and age it'd be nice to have a `ResizeObserver` polyfill be provided as a prop rather than included in the bundle.

**Comment by jaredLunde** [comment]
I would accept a PR for this btw

**Comment by trinhcongduc** [comment]
I am trying to add the library to my RemixJS app. but i got same issue : **ReferenceError: ResizeObserver is not defined**
