### ISSUE TITLE
Why does it unmount items that are in a viewport?

### ISSUE THREAD

**Issue by zernie** [jaredLunde/masonic#163]
After rendering a masonry deck, it almost immediately re-mounts them. I don't use any options besides render and items. Is this an intended behavior?

**Comment by jaredLunde** [comment]
Yes

**Comment by zernie** [comment]
but why?

**Comment by jaredLunde** [comment]
Read the comment in the thread you replied to. It's how the algorithm works. Use something else if you don't like it ✌🏼
