### ISSUE TITLE
Wonder can "masonic" works well in the masonry list is in an absolute container?

### ISSUE THREAD

**Issue by tcf01** [jaredLunde/masonic#167]
**Is your feature request related to a problem? Please describe.**
I hv wrapped <MasonryScroller/> in an absolute positioned container since this is the requirement. The items can be rendered but the scrollbar isn't working

**Describe the solution you'd like**
I can scroll down and seeing the contents I hv.

**Comment by jaredLunde** [comment]
https://codesandbox.io/s/masonic-inside-of-a-scrollable-div-example-k9l6c?file=/src/index.js

**Comment by tcf01** [comment]
Hi @jaredLunde. Thank you for the quick updates! The use case for me is like this. I need to wrap the masonic scrollable content in an absolute positioned container. I hv tried here but the scrollable content has gone. Is there anything I hv missed?

[ref link](https://codesandbox.io/p/sandbox/masonic-inside-of-a-scrollable-div-example-forked-rryjxc?file=%2Fsrc%2Findex.js)

**Comment by jaredLunde** [comment]
There shouldn't be any issues. You could write your own useSize/useScroller hooks, add a dependency from any other hook package, or copy/paste from the library.

**Comment by tcf01** [comment]
@jaredLunde  Thank you for your help. I managed to figure that out.
