### ISSUE TITLE
Broken demo project

### ISSUE THREAD

**Issue by molinch** [jaredLunde/masonic#18]
Hello, the demo project is currently broken, see:

![image](https://user-images.githubusercontent.com/5130190/83671044-57a06280-a5d4-11ea-976a-02a4be8a45c1.png)

Maybe @-ui/system has changed since you wrote the demo ?

**Comment by jaredLunde** [comment]
Ugh, I actually think this is a CodeSandbox issue. I'll see about fixing it.

**Comment by jaredLunde** [comment]
https://twitter.com/CompuIves/status/1268306584213610497

Ives has fixed the issue! Thanks for the report and looking out, though!
