### ISSUE TITLE
perfomance

### ISSUE THREAD

**Issue by nikitapilgrim** [jaredLunde/masonic#2]
https://www.paulirish.com/2012/why-moving-elements-with-translate-is-better-than-posabs-topleft/
why do you use positioning and not transform?

**Comment by jaredLunde** [comment]
So this is definitely true for transitions, but I'm not convinced it'd be a big performance boost for regular positioning. I'd like to see some data on that to know if there would be a meaningful effect on render performance. Absent that, positioning is more idiomatic.
