### ISSUE TITLE
Scrolling column shifting glitches

### ISSUE THREAD

**Issue by dj-stormtrooper** [jaredLunde/masonic#21]
**Describe the bug**
First of all, thanks for the great library, really enjoyed it. I've found some glitches with column shifting  appear when scrolling up and down, could you help me with workaround? 

**To Reproduce**
Actually it happens in project's codesandbox as well, https://imgur.com/a/bDvogOK

1. Go to https://codesandbox.io/s/0oyxozv75v?file=/src/index.js (official demo)
2. Resize demo box to see 4-5 columns with cats
3. Scroll in demo for 3-4 pages and then just up in down for some time til glitches appear

**Expected behavior**
No glitches

**Desktop (please complete the following information):**
- OS: tested in MacOs and WIndows
- Browser: Chrome

**Comment by jaredLunde** [comment]
[I've been discussing this here](https://twitter.com/jaredLunde/status/1273292523935379456) as well. I am fairly certain that this is a result of second phase measurement not happening when the container is quickly scrolled (which is expected - ultimate you want the renderer to favor the currently visible items). This issue doesn't happen if you scroll down at a normal pace and then scroll back up or scroll up and down over cells with up-to-date values in the cache. I've made a note to explore this further to see if there's anything I can do to mitigate it, but I'm uncertain it will bare fruit.

**Comment by dj-stormtrooper** [comment]
Thank you, setting height manually (in my case via padding in %, based on the image ratio) actually helped

**Comment by soly2014** [comment]
any one solved this problem ??

**Comment by alexisdrakopoulos** [comment]
Any update on this problem? Setting the height doesn't work very well in my case

**Comment by Weiting-Zhang** [comment]
> Any update on this problem? Setting the height doesn't work very well in my case

+1, not working in my case.  @jaredLunde Could we have a fix plan?
