### ISSUE TITLE
TypeError Invalid value used as weak map key

### ISSUE THREAD

**Issue by miqdadfwz** [jaredLunde/masonic#23]
**Describe the bug**
Hi Jared, thank you for putting your effort for initiating this library, really loved it. First of all, hope the image below would make more clear about my application that I'm trying to build.

![pokemon-masonry](https://user-images.githubusercontent.com/43945767/86309939-12109d00-bc47-11ea-827c-147b381b2526.png)

Well, I have found a bug throwing the error when trying to re-mount the Masonry component instance by changing the between tabs. Really need your insight here, thanks!

**To Reproduce**

1. Open [this sandbox](https://codesandbox.io/s/github/miqdadfwz/pokemon-masonry/tree/master/?fontsize=14&hidenavigation=1&theme=dark)
2. Scroll down for 2-4 pages.
4. Click different tab.
5. Try to explore by scrolling down, changing another tab or coming back to previous tab.
6. You will see the application intermittently throwing `typeerror Invalid value used as weak map key`. I think the error comes from here https://github.com/jaredLunde/trie-memoize/blob/master/src/index.ts#L77

**Expected behavior**
No error happens

**Screenshots**
![Screen Recording 2020-07-02 at 09 39 17](https://user-images.githubusercontent.com/43945767/86310889-46855880-bc49-11ea-80b9-505eafeee9d6.gif)

**Desktop (please complete the following information):**

- OS: MacOS Catalina
- Browser: Chrome
- Version: 83.0.4103.116 (Official Build) (64-bit)

**Comment by miqdadfwz** [comment]
Well apparently it is solved by adding key props as described here https://codesandbox.io/s/masonic-w-react-router-example-2b5f9?file=/src/index.js. Will close this issue

**Comment by jaredLunde** [comment]
Thanks for the thorough report regardless! I really appreciate it. I will work on a release where this error message is more descriptive.

**Comment by zernie** [comment]
Adding a key prop doesn't always help.

**Comment by jaredLunde** [comment]
You're using unique keys that change in the same render the list items do?

**Comment by justisom** [comment]
> You're using unique keys that change in the same render the list items do?

They were all unique numeric values. I did end up resolving the issue.
I moved this block of code 
`
    const { width, height } = useSize(containerRef);
    const { scrollTop, isScrolling } = useScroller(containerRef);
    const positioner = usePositioner(
      {width, columnWidth: 172, columnGutter: 8},
    );
    const resizeObserver = useResizeObserver(positioner);
`

which was sitting at the top level of my page component to the function where I was using calling myMasonry. Not sure why. I thought perhaps this might have some effect on the grid position/size but not on how the items were being populated in the grid.

**Comment by zernie** [comment]
We don't have that but still experience the issue sometimes.

**Comment by lidroid** [comment]
This problem is bound to occur when the number of items is small

**Comment by lidroid** [comment]
> This problem is bound to occur when the number of items is small

This problem is inevitable when the number of items is variable and small and no scroll bar is required

**Comment by jaredLunde** [comment]
? Why. I have literally never run into the error.

**Comment by zernie** [comment]
we have dozens of items btw. I think it usually happens when the number of items increases

**Comment by lidroid** [comment]
> ? Why. I have literally never run into the error.

You can try something like this: fetch a few pages of data from the server, then re-query with conditional filtering only returns less than one page of data, and the problem should recur

**Comment by jaredLunde** [comment]
Yes, that is the expected behavior. You have to blowout the grid with a key prop or add a dependency array to the usePositioner hook

**Comment by vincexiv** [comment]
Add key={crypto.randomUUID()} to the Masonry component. It should look like this eventually; 
```
      <Masonry
        key={crypto.randomUUID()}
        // Your other props
      />
```

Please note that this makes Masonry to create an entirely new layout with the updated data

**Comment by jaredLunde** [comment]
> Add key={crypto.randomUUID()} to the Masonry component. It should look like this eventually;
> 
> ```
>       <Masonry
>         key={crypto.randomUUID()}
>         // Your other props
>       />
> ```
> 
> Please note that this makes Masonry to create an entirely new layout with the updated data

no one should do this

**Comment by vincexiv** [comment]
Yeah, it's super hacky, but it worked in my case; unlike all the solutions provided above (I tried them). That said, I would appreciate a better way to go about it

**Comment by joebnb** [comment]
wired i also facing this issue, in my case if the items data is init outside of component, when change page and back，will throw weak make key(maybe because these data change can't tracking by react states)

**Comment by zernie** [comment]
@joebnb this is the only solution that worked for me: https://github.com/jaredLunde/masonic/issues/12#issuecomment-621900468

it does have some drawbacks, like flashing, though
