### ISSUE TITLE
Delete item from Arraylist showing Uncaught TypeError: Invalid value used as weak map key

### ISSUE THREAD

**Issue by Sandeep0695** [jaredLunde/masonic#24]
Hey, 
When i delete an item which position at 0 Zero index from an array of 10 items then we have no any issues but if i want to delete an item from 4th or other index (Other then 0 index) then its show weak map key error.
i am using splice method to delete item
E.g 	currentDataList.splice(4, 1);

**Comment by jaredLunde** [comment]
See https://github.com/jaredLunde/masonic/issues/12

**Comment by Sandeep0695** [comment]
Overall , Currently we don't have solutions of this issues ?

**Comment by jaredLunde** [comment]
It's not technically an issue and thus there is no solution apart from what I suggested in that thread

**Comment by jumodada** [comment]
@Sandeep06Dev  
In fact you only need to change the key of the whole component when the length of the data changes

```
    const fixedKey = useMemo(() => {
        return itemsCount + Date.now();
    }, [itemsCount]);

 <Masonry columnCount={4} key={`${fixedKey}`} items={modelList?.data || []} render={MasonryCard}/>
```
