### ISSUE TITLE
Failed to compile ('=' expected.  TS1005)

### ISSUE THREAD

**Issue by johnrees** [jaredLunde/masonic#25]
**Describe the bug**

After importing Masonic into a Typescript create-react-app project, the build fails due to an error in the list.d.ts type file?

**To Reproduce**

Clone this minimal create-react-app repository with the README example added in [`src/App.tsx`](https://github.com/johnrees/failing-masonic-build/blob/master/src/App.tsx)

https://github.com/johnrees/failing-masonic-build

`run yarn start`

**Expected behavior**

The app should run on http://localhost:3000

**Screenshots**
![Screenshot 2020-07-08 at 7 26 50 PM](https://user-images.githubusercontent.com/601961/86956798-984e4700-c151-11ea-8907-9e3b4dad53ec.png)

**Desktop (please complete the following information):**

- OS: macOS 10.15.4
- Browser N/A

**Additional context**

- Yarn 1.22.4

**Comment by jaredLunde** [comment]
You have to use TypeScript >=3.8 for the `import type` syntax.

I do not plan on fixing this.

**Comment by johnrees** [comment]
Ah hah! That's it! Thanks :)

**Comment by jaredLunde** [comment]
Anytime!
