### ISSUE TITLE
Layout overlapping on latest Chrome Version: 84.0.4147.89

### ISSUE THREAD

**Issue by PaulMyhr** [jaredLunde/masonic#28]
The Chrome update on July 15th to version 84.0.4147.89 breaks masonic's ability to properly layout items vertically without overlapping when the item heights are measured dynamically

See here: https://codesandbox.io/s/0oyxozv75v

happens on your sandbox too in newest chrome

**Comment by PaulMyhr** [comment]
Possibly an issue in use-resize-observer.ts:

the code makes a decision about how to measure an element's height based on whether ResizeObserver supports the borderBoxSize property. In Chrome 83 it doesn't, but in Chrome 84 it does - but the code expects the borderBoxSize property to be an object, and in Chrome 84 it's an array of ResizeObserverSize objects

**Comment by jaredLunde** [comment]
Thanks for the report! I will fix this tonight.

**Comment by jaredLunde** [comment]
This has been fixed in `3.3.2`. Thanks again for reporting and digging into the issue. Really helps!

**Comment by PaulMyhr** [comment]
Awesome 👍  thanks - while I possibly have your attention, would you accept a PR to make tabIndex accept string again so it can be set to "none". I've noticed that the type changed to numeric for tabIndex in the masonry component in v3.3.0 and can't seem to turn it off

**Comment by jaredLunde** [comment]
Does `-1`  work for you in this case?

**Comment by jaredLunde** [comment]
More to the point, is `"none"` a valid value?

**Comment by PaulMyhr** [comment]
Yah good call -1 works - "none" used to be in CSS but looks not needed thanks
