### ISSUE TITLE
Infinite scroll has render issues

### ISSUE THREAD

**Issue by robertcasanova** [jaredLunde/masonic#29]
The infinite scroll behavior is working fine while scrolling down to new items but when you try to scroll top has some issue.

You can reproduce this issue also on the [Infinite Scroll example](https://codesandbox.io/s/useinfiniteloader-example-vn30p?file=/src/index.js)

Try to scroll down for a while and then scroll up.

- OS: OSX
- Browser: Chrome
- Version 83

**Comment by jaredLunde** [comment]
Not sure what you're referring to. Looks completely fine to me.

**Comment by robertcasanova** [comment]
Hi, @jaredLunde thx for your reply. The issue is more evident if you try reducing the window to see the two columns layout. One column "jumps".

**Comment by jaredLunde** [comment]
https://github.com/jaredLunde/masonic/issues/21
