### ISSUE TITLE
scrolling calculation

### ISSUE THREAD

**Issue by nikitapilgrim** [jaredLunde/masonic#30]
can I make a scrolling calculation at the inside of the container rather than from scrolling window?

**Comment by jaredLunde** [comment]
Not entirely certain what you mean so feel free to clarify if the below example doesn't help you:
https://codesandbox.io/s/masonic-inside-of-a-scrollable-div-example-k9l6c?file=/src/index.js

**Comment by nikitapilgrim** [comment]
I'd like to implement a scroll-snap

**Comment by nikitapilgrim** [comment]
> Not entirely certain what you mean so feel free to clarify if the below example doesn't help you:
> https://codesandbox.io/s/masonic-inside-of-a-scrollable-div-example-k9l6c?file=/src/index.js

thank you for fast reply

**Comment by nikitapilgrim** [comment]
Excuse me, do you have any idea if it's possible? Without changing the API library
me need make virtualize scroll-snap container
and specify for children scroll-snap-align: start;

**Comment by jaredLunde** [comment]
I doubt it's going to be possible in a virtualized list/grid. I tried to do a basic example and it doesn't work anything like you would expect.
