### ISSUE TITLE
Development env: TypeError: Cannot assign to read only property 'name' (ie: width, minHeight) of object '#<Object>'

### ISSUE THREAD

**Issue by PaulMyhr** [jaredLunde/masonic#31]
Error only seems to propagate when running react/node in development rather than production.

In use-masonry.tsx:

children.push(
        <ItemComponent
          key={key}
          ref={setItemRef(index)}
          role={itemRole}
          style={
            typeof itemStyle === 'object'
              ? Object.assign(phaseOneStyle, itemStyle)
              : phaseOneStyle
          }
        >
          {createRenderElement(RenderComponent, index, data, columnWidth)}
        </ItemComponent>
      )

Throws the error: TypeError: Cannot assign to read only property 'name' of object '#<Object>', when you supply the masonry component your own itemStyle object

Its fixed with Object.assign({}, phaseOneStyle, itemStyle) but if the intent is to write to phaseOneStyle instead of a new object, it should probably be made writable

**Comment by jaredLunde** [comment]
It's technically safe to mutate the object but for sanity's sake I opted to create a new object and released in `3.3.3`. Thanks for another great report.

**Comment by PaulMyhr** [comment]
Thanks a bunch! 👍
