### ISSUE TITLE
How to use Memorize /Memo with useInfiniteLoader

### ISSUE THREAD

**Issue by Sandeep0695** [jaredLunde/masonic#34]
Hi the brilliant jaredLunde.

How to Memorize item when using hook useInfiniteLoader.

Any example or docs ?

**Comment by jaredLunde** [comment]
Not sure exactly what you're trying to accomplish here. Feel free to add more context and I will try to help.

**Comment by Sandeep0695** [comment]
**Sir, Basically i need Combination of**  Memorize until (   https://codesandbox.io/embed/github/bvaughn/react-window/tree/master/website/sandboxes/memoized-list-items?codemirror=1 ) 

 **along with**
useinfiniteloader ( https://codesandbox.io/embed/useinfiniteloader-example-vn30p?file=/src/index.js&codemirror=1 ) 
 Can you create or share some code snippets with memories and use infinite loader. 


Actually i dont want to reload/render 'Fakecard' on scroll up or down  ( If the cache of that fakecard item is already available in Memorize.)

**Comment by jaredLunde** [comment]
Memoizing like this isn't going to give you any performance gains in Masonic. [It already memoizes under the hood](https://github.com/jaredLunde/masonic/blob/master/src/use-masonry.tsx#L368)

**Comment by Sandeep0695** [comment]
OK.. Thanks men ..
