### ISSUE TITLE
Overlaying issue with MasonryScroller 

### ISSUE THREAD

**Issue by Sandeep0695** [jaredLunde/masonic#35]
Hi Sir,
I am using MasonryScroller . i don't have any fixHeight Value in item array list, I am populating image from an external source, Now when image get loads then One item is overlaying on other one .

To understand more and to see what's the problem please visit https://codesandbox.io/s/masonryscroller-example-sx3t2?file=/src/index.js  .

**Comment by jaredLunde** [comment]
You'll need to connect a [`useResizeObserver()`](https://github.com/jaredLunde/masonic#useresizeobserverpositioner) hook to handle dynamic heights

**Comment by Sandeep0695** [comment]
Sir, Can you add a useResizeObserver() on  https://codesandbox.io/s/masonryscroller-example-sx3t2?file=/src/index.js .  ?
Thanks for fast reply..

**Comment by jaredLunde** [comment]
Here you go, my friend: https://codesandbox.io/s/masonryscroller-example-s7897?file=/src/index.js

**Comment by Sandeep0695** [comment]
Your are simply awesome ..
