### ISSUE TITLE
How to share IsScrolling props to Component. 

### ISSUE THREAD

**Issue by Sandeep0695** [jaredLunde/masonic#36]
Hi sir, 

I want to get isScrolling attribute of useScroller in my fakeCard Functional component.

Currently, i m getting data props only in fakecard in which i can get item values, index nd width..

Code snippets. 
const FakeCard = props => {
 // NEED isScrolling HERE, Basically on scrolling i want to show loading  div box instead of card. 
 // console.log(props);
  
  return (
  <div className={style("card")} style={{ height: props.data.height }}>
    <span children={props.data.id} />
  </div>
);}

**Comment by jaredLunde** [comment]
You need to combine the `useScroller()` hook with something like this: https://twitter.com/jaredLunde/status/1272655668701310976

**Comment by jaredLunde** [comment]
So like 
```js
const CardWithIsScrolling = React.useCallback(
  props => <FakeCard 
     {...props} 
     isScrolling={isScrolling}
  />, 
  []
)

return useMasonry({render: CardWithIsScrolling, ...other props})
```

**Comment by Sandeep0695** [comment]
Sir, 
Can i get some code snippets by overriding this 
https://codesandbox.io/s/usemasonry-example-3pcg9?file=/src/index.js

**Comment by jaredLunde** [comment]
https://codesandbox.io/s/usemasonry-example-3pcg9?file=/src/index.js
