### ISSUE TITLE
Miscalculating when re-render the large of the dataset

### ISSUE THREAD

**Issue by miqdadfwz** [jaredLunde/masonic#37]
**Describe the bug**
Hi Jared, thank you for putting your effort to this library, it really helped me. However, I encountered an issue when re-render the large amount of items. Seems there is wrong `y` position calculation which implies the items is invisible.

**To Reproduce**

1. Go to this [sandbox](https://codesandbox.io/s/cool-wilbur-s88xh)
2. In the preview window, scroll down until reach a large enough of `y` position value.
3. Click to the next tab (the component attached in top of the viewport).
4. Click back to the previous tab, **It will remember the last scroll `y` position**. You will see the items are clearly invisible because *maybe* the `y` position value is wrong.

**Expected behavior**
The items are visible.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version 84.0.4147.105 (Official Build) (64-bit)

**Comment by miqdadfwz** [comment]
UPDATE: apparently if you change the viewport size, it gets resolved and the items become visible. Is it because resizeobserver?

**Comment by jaredLunde** [comment]
Not able to reproduce this in any browser.

**Comment by miqdadfwz** [comment]
maybe this can help 

![Screen Recording 2020-08-03 at 13 03 30](https://user-images.githubusercontent.com/43945767/89150946-f53ef080-d589-11ea-9546-b49e841f1456.gif)

**Comment by Sandeep0695** [comment]
Try usePositioner() hook along with dependence
e.g https://github.com/jaredLunde/masonic#usepositioneroptions-deps

**Comment by jaredLunde** [comment]
This is a pretty complex example so it's hard to nail down exactly what your issue is without occupying a significant amount of my time. I think @Sandeep0695 is probably on the right track. Some examples of what they're talking about:

- https://codesandbox.io/s/masonic-w-react-router-example-2b5f9?file=/src/index.js
- https://codesandbox.io/s/masonic-w-react-router-and-advanced-config-example-8em42?file=/src/index.js

**Comment by miqdadfwz** [comment]
Hi @Sandeep0695 I have tried using `usePositioner()` [here](https://codesandbox.io/s/intelligent-ganguly-jr5bf?file=/src/components/MasonryV2/Col/index.tsx) but unfortunately it doesn't resolve the issue (or maybe I'm missed something?).

Anyway, I'm not using react-router for the navigation, I just memorize the last scroll position when user navigate to another tab/page, so when the user come back to the previous tab/page, it will come back to its last scroll position.

**Comment by Sandeep0695** [comment]
I had override your code snippet, Look at that i think this will help you @miqdadfwz 
 https://codesandbox.io/s/angry-breeze-q0fcn?file=/src/components/MasonryV2/Col/index.tsx
