### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by khmm12** [jaredLunde/masonic#39]
**Describe the bug**
`useResizeObserver` usage causes error `ResizeObserver loop limit exceeded`.

**To Reproduce**

1. Use `useResizeObserver`
2. Subscribe to global errors `window.onerror = (errorMessage) => {}`  
3. Try to resize browser window/change device or viewport size via browser dev-tools.

**Expected behavior**
`useResizeObserver` shouldn't cause the error.

**Additional context**

- `ResizeObserver` usage to resize other elements based on size of the observed element causes some "bounce" for first few frames. 
- Browsers and canonical polyfills are smart enough to break infinite loop or detect that they're not able to deliver all observation results within a single frame.

The issue can be easily solved via rAF usage.

```js
let frameId

const cancelFrame = () => {
  if (frameId !== undefined) {
    cancelAnimationFrame(frameId)
    frameId = undefined
  }
}

const observer = new ResizeObserver(() => {
  cancelFrame()
  frameId = requestAnimationFrame(() => {
    /* Your code */
  })
})

const dispose = () => {
  cancelFrame()
  observer.disconnect()
}

observer.observe($element)
```

or even better with `raf-schd`

```js
const requestUpdates = rafSchd(() => {
  /* Your code */
})

const observer = new ResizeObserver(requestUpdates)

const dispose = () => {
  requestUpdates.cancel()
  observer.disconnect()
}

observer.observe($element)
```

**Comment by jaredLunde** [comment]
Is this error not benign? Why should I care if it happens?

**Comment by khmm12** [comment]
@jaredLunde 👋

> Is this error not benign? Why should I care if it happens?

it's raised out of code execution scope, that's why can't be handled via try/catch. It won't break neither ResizeObserver instance, nor browser. Browsers are not Node.js where `uncaughtexception` crashes entire process. Actually the error tells developers "You're doing something wrong, we resolved infinite loop to prevent the browser crash".

But even if we suppose that it can be ignored, what some developers do.

- It blocks the UI thread with useless work for entire frame. There is no any sense to re-calculate and resize elements more than once per frame.
- It floods error report trackers and browser automation tools.

**Comment by jaredLunde** [comment]
Is there any risk that this misses size updates if it is throttled with something like `raf-schd`?

**Comment by khmm12** [comment]
> Is there any risk that this misses size updates if it is throttled with something like raf-schd?

No. Because `raf-schd` doesn't cancel anything on repeated function call.

So equivalent code should look something like that:

<details>
<summary>Snippet</summary>

```js
let frameId

const cancelFrame = () => {
  if (frameId !== undefined) {
    cancelAnimationFrame(frameId)
    frameId = undefined
  }
}

const requestUpdate = () => {
   /* Your code */
}

const scheduleUpdate () => {
  if (frameId !== undefined) return

  frameId = requestAnimationFrame(() => {
     frameId = undefined
     requestUpdate()
  })
}

const observer = new ResizeObserver(scheduleUpdate)

const dispose = () => {
  cancelFrame()
  observer.disconnect()
}

observer.observe($element)
```
</details>

But nevertheless I'd pick `raf-schd`, because it's tiny, wide used and with a high probability there will be already in a bundle.
