### ISSUE TITLE
Incompatible TypeScript types for onRender and useInfiniteLoader

### ISSUE THREAD

**Issue by DimitryDushkin** [jaredLunde/masonic#43]
**Describe the bug**
Masonry component has such prop:
```ts
  /**
   * This callback is invoked any time the items currently being rendered by the grid change.
   */
  onRender?: (
    startIndex: number,
    stopIndex: number | undefined,
    items: Item[]
  ) => void
```
and it is incompatible with callback, that returns useInfiniteLoader:
```ts
export declare type LoadMoreItemsCallback<Item> = (
  startIndex: number,
  stopIndex: number,
  items: Item[]
) => any
```
at stopIndex. So there is TS error.

Is  `stopIndex: number,` or `stopIndex: number | undefined,` ?

- Version 3.3.8

PS: thank you for great lib! 👍

**Comment by jaredLunde** [comment]
Dang, my bad. Will put out a fix for this today.

**Comment by DimitryDushkin** [comment]
wow, great, thx!
