### ISSUE TITLE
usePositioner doesn't update instance in StrictMode

### ISSUE THREAD

**Issue by khmm12** [jaredLunde/masonic#44]
**Describe the bug**

`usePositioner` doesn't return a new instance when deps or size changes.

**To Reproduce**

1. Use React `StrictMode`.
2. Use `useResizeObserver`.
3. See nothing works.

https://codesandbox.io/s/useresizeobserver-example-forked-6y3s2

**Additional context**

https://github.com/jaredLunde/masonic/blob/9ebb69c1b20b47a5da7f275461fb080f134f9d6e/src/use-positioner.ts#L40

Developers can't use `useRef` to update depending state from props (see Derived State), because it causes side-effects. 

In StrictMode React renders the component twice to detect wrong behavior.

[The right implementation](https://github.com/jaredLunde/masonic/pull/41/files).

**Comment by jaredLunde** [comment]
Yeah you're mostly correct. `ref.current = prev` in `useEffect()` will work just the same. Definitely should not have to put this state.

**Comment by jaredLunde** [comment]
That's what this would lead me to believe anyway https://overreacted.io/a-complete-guide-to-useeffect/#each-render-has-its-own-effects

**Comment by khmm12** [comment]
@jaredLunde 

This way you won't archive "get derived state" behaviour.

There is recommended and wide-used approach.

- https://en.reactjs.org/docs/hooks-faq.html#how-do-i-implement-getderivedstatefromprops
- https://github.com/facebook/react/blob/master/packages/use-subscription/src/useSubscription.js

**Comment by jaredLunde** [comment]
For sure, your original PR reminded me of the `useSubscription()` source. Just didn't properly understand what the purpose was when I saw it the first time.

**Comment by jaredLunde** [comment]
Do you know if there's a proper way to test against StrictMode? Adding `{wrapper: ({children}) => <React.StrictMode>{children}</React.StrictMode>}` didn't seem to change anything.

**Comment by khmm12** [comment]
@jaredLunde 

> Do you know if there's a proper way to test against StrictMode? Adding {wrapper: ({children}) => <React.StrictMode>{children}</React.StrictMode>} didn't seem to change anything.

It does nothing with react-test-renderer which is used by react-hooks-testing-library ;-)

But should makes difference with @testing-library/react as far as it uses ReactDOM

**Comment by jaredLunde** [comment]
Ahh. That's too bad. Published your fix in `3.3.9` and your CodeSandbox works now :) Thanks again for the lesson.

**Comment by khmm12** [comment]
@jaredLunde BTW you should try to check within concurrent mode 😉

Concurrent mode is the near future, but many libraries is still incompatible.

**Comment by jaredLunde** [comment]
Definitely! My original sandboxes had it, but then this happened: https://github.com/jaredLunde/masonic/issues/13

**Comment by khmm12** [comment]
Yeah, since some time React team ships suspense in experimental package only 🙂

**Comment by jaredLunde** [comment]
Right, but I haven't been able to get `react@experimental` or `react-dom@experimental` to install in CodeSandbox 🤔 Whenever I install the tag it defaults to the 17 rc. You can see it in the left panel [here](https://codesandbox.io/s/0oyxozv75v?file=/src/index.js). Do you happen to know what's going on there?

**Comment by jaredLunde** [comment]
Nevermind. Adding an `unstable_` prefix to `createRoot()` worked 👍
