### ISSUE TITLE
How disable the border?

### ISSUE THREAD

**Issue by DiSayThis** [jaredLunde/masonic#48]
Hello, how do I disable the border when clicking on a component Masonry?
![Безымянный](https://user-images.githubusercontent.com/45077374/94702610-9c4fc680-0346-11eb-9d68-9f9af248071f.png)

**Comment by jaredLunde** [comment]
Add `outline: none` to `:focus` styles for the container or add a `tabIndex={-1}` prop

**Comment by DiSayThis** [comment]
Thanks
