### ISSUE TITLE
quickly drag the scroll bar appears blank page

### ISSUE THREAD

**Issue by onejustone** [jaredLunde/masonic#49]
**Describe the bug**

hi，jaredLunde，thank you very much for providing such a good work，I met a problem，quickly drag the scroll bar appears  white screen。

**Expected behavior**

quickly scrolling can smoothly render elements

**Screenshots**

![fast-scroll-bug-demo](https://user-images.githubusercontent.com/14921412/95932314-1e87c280-0dfe-11eb-9dd7-f3ace0425cf2.gif)

an official example is the same，[masonic inside of a scrollable div example](https://codesandbox.io/s/masonic-inside-of-a-scrollable-div-example-k9l6c) ，If `item` is a complex react component  not just a simple element, the white screen will be more serious. 

Is there any good solution to this situation?

**Desktop (please complete the following information):**

- OS: MacOS Catalina
- Browser [chrome v85.0.4183.121]

Thank‘s again for providing such a great work！！！

**Comment by jaredLunde** [comment]
It's a virtualized grid, I'm not sure what you're expecting.
