### ISSUE TITLE
Masonry didn't render new items

### ISSUE THREAD

**Issue by tqdung** [jaredLunde/masonic#51]
**Describe the bug**
Dear Mr. Jaredlunde
I've my own infinityload api which is fetching new data and update the list items passed by props to Masonry component, I've check the network, api was fired and new data was loaded, but it not update the UI (just render some Item as the first time), I also try to implement useInfinityload but it not help.

**Expected behavior**
I just want to update layout when ever items was updated, maybe it's not a bug, but in my case it not work. I hope you read my question. This is my email: tqdungit97@gmail.com, if you see my question, please reply me or contact with me. Thank you very much

**Screenshots**

<img width="555" alt="Screen Shot 2020-10-18 at 23 13 46" src="https://user-images.githubusercontent.com/37869666/96373575-9efc4980-1197-11eb-8c36-7ca81a21058e.png">
<img width="618" alt="Screen Shot 2020-10-18 at 23 14 30" src="https://user-images.githubusercontent.com/37869666/96373582-b4717380-1197-11eb-9960-f242c29cf8c2.png">

**Additional context**

**Comment by jaredLunde** [comment]
Sorry, I don’t answer unpaid support inquiries. The library is well-documented and typed. You’ve just got to figure it out on your own. If you do find a bug feel free to submit.
