### ISSUE TITLE
Using masonic with some animation libraries

### ISSUE THREAD

**Issue by d-ivashchuk** [jaredLunde/masonic#53]
First of all thanks a lot for `masonic` - is precisely solved my problem in an easy and elegant way!

I was curious if current implementation allows to integrate easily with some animation library like `framer-motion`, `react-spring` or similar to achieve enter exit animations of the cards(I am more worried about virtualised part here). The use case is quite simple - I have the list of cards within masonic. I filter them and some of the cards disappear, I remove filters - they appear back.

Maybe there are examples of this in the wild - didn't find anything useful.

Thanks for the answer!

**Comment by jaredLunde** [comment]
This likely won't ever work. Answered something similar here: https://github.com/jaredLunde/masonic/issues/11

**Comment by hdehal** [comment]
@d-ivashchuk I am using `framer-motion` with `masonic` and `Next.js`

I'm still troubleshooting, but it does not animate on initial pageload, but only when I come back to the page (granted I'm using static pages via Next.js).

````
import { motion } from "framer-motion"
import { Masonry } from 'masonic'
...
    const MasonryCard = ({ index, data: { id }, width }) => (
        <motion.div
            variants={item}
            whileHover={{
                scale: 1.02,
                transition: { duration: 0.1 },
            }}
            whileTap={{ scale: 1.02 }}
        >
            <img src={"/images/rsfp/" + id + ".jpg"} width={width} />
        </motion.div>
    )
````
P.S. Thank you @jaredLunde for all your hard work on this project! It was super easy to install and use.

**Comment by d-ivashchuk** [comment]
@hdehal awesome that you got it working to some extent at least! If you'll find the way to make it work in a stable and visually okeish way - please ping me.
