### ISSUE TITLE
useInfiniteScroller Example - jump on scroll (not similar to older issues)

### ISSUE THREAD

**Issue by lcampanis** [jaredLunde/masonic#54]
Great module, great patience, so thank you!

**Describe the bug**
In the example provided, when scrolling back up there is a jump on the cells.
https://codesandbox.io/s/useinfiniteloader-example-vn30p?file=/src/index.js

Understandably, the images in this example have no "height" set, so it makes sense when scrolling back up to have to recalculate. 

However, the same happens when the image heights are set correctly for all images in cells.

Having looked at all Masonic examples and docs, it seems the solution isn't clear and have to ask. 
A few thoughts:
- It feels like the cell's height isn't _cached_ correctly (even with devTools closed, where images should be cached by the browser)
- or that the cell's height isn't _calculated_ in full, ie. calculating the total including borders, margins, paddings, don't make up the full, actual height of the cell

We've tried with `<Masonry />` but also with a custom implementation based on the core Masonic component; the problem persists.

Would you please advise in this example how to avoid the jump on scroll up? 
Thank you.

**To Reproduce**

1. Go to https://codesandbox.io/s/useinfiniteloader-example-vn30p?file=/src/index.js (Chrome)
3. Scroll down a few pages
1. Scroll back up, see cells jumping

**Expected behavior**
When setting image heights, the cells shouldn't jump when scrolling up.

**Desktop (please complete the following information):**
- OS: Mac
- Browser Chrome
- Version Latest

**Comment by lcampanis** [comment]
`<Masonry key />` was being set on each new page load, so ensure this doesn't happen, so Masonic cache actually works as expected.
It seems all works well, of course Merphy's law... 
Thanks

**Comment by lcampanis** [comment]
Having investigated the issue a bit more, the issue persists when coming back to the masonry grid page and using scrollToIndex for an item located a few pages down.

Although dimensions are specified on images, scrolling always works as it should, the height of each cell in the non-visible pages aren't calculated correctly. Because of this, as you scroll up the cell heights re-adjust correctly and the cells jump (Scrolling down works fine).

This can be tested and replicated in the example code sandbox in the description above, once height have been set correctly for all images and a scrollToIndex is added.

It does feel that the `itemHeightEstimate` is causing this. 
Rather than actually calculating the height of each page's cells on load, it uses the estimate, but in cases where cells are not all of equal height, the jump always happens.
![image](https://user-images.githubusercontent.com/670954/102343949-de7ec080-3fa3-11eb-81c0-1258bd9699f6.png)
@jaredLunde there's a few ways to tackle this on load (to some expense of course). 
Ideally we should let all pages show once, calculate grid height in full,  scrollToIndex, then and only then apply virtualization to as per overscanBy.. Any thoughts on how to overcome this?

**Comment by jaredLunde** [comment]
Unfortunately, I disagree on all points. The size calculation has to be a lazy evaluation. If one wanted to duck virtualization, they could just set the `overscanBy` prop to infinite. The library really isn't built for these cases. It's built for the scale of Pinterest so you can infinitely scroll thousands of items. Most of these types of issues that I see in the tracker come from a lack of understanding about project goals. You think you want X but you don't fully understand the tradeoff to using it. Calculating the full grid height on load is just asinine. There's no other way to put it. There's no point in virtualizing if you do that. There would be substantial jank in doing so for long item arrays. 

Lastly, while you can technically add images that are lazily measured, it's an absolutely terrible idea to do so. I'd never do that in prod. You should know the dimensions of your images and calculate their `width` and `height` properties based on the `itemWidth` prop that is passed to the render function. These are all very easy things to implement and I've done it at great scale hitting millions of users w/ thousands of grid cells and voila, I've faced none of the issues you all talk about.

**Comment by lcampanis** [comment]
@jaredLunde very kind, thank you for getting back so fast. Only trying to help find some direction on this issue.

All images have their heights and widths set from the start, everything is setup as you'd expect it in your docs, no problem with that at all. We have also compared the way it works with Pinterest and it's very similar. Only differences are:
1. Items on Pinterest are rendered in the same column and position at all times, so you'd find it where it was before (x, y and column)
2. Only after visiting a product and coming back to the grid, you'd find the product in another column and position, though the problem is only about scrolling up

The issue is only visible on scroll up in the same way as in the example here: 
https://codesandbox.io/s/useinfiniteloader-example-vn30p?file=/src/index.js
Only difference is image heights are all correctly set.

The scenario is visible when clicking on a product and then going back to it on the grid.
Here's Masonic in production https://artlimes.com/buy-art/paintings

**Comment by jaredLunde** [comment]
You are speaking about a UX issue IMO. You're taking someone to a new page from an infinite list and expecting them to be able to navigate back perfectly.. That's never going to work 100% as you expect. Open it in a modal or something. Problem solved. Or use pages instead of infinite scrolling.
