### ISSUE TITLE
Expose interval tree module

### ISSUE THREAD

**Issue by bnjmnt4n** [jaredLunde/masonic#57]
Hey, firstly, thanks a lot for this great package!

Exposing most of the functionality as hooks has made it very modular and easy to customize. Right now, I'm attempting to implement a custom positioner, and would love to use masonic's interval tree. However, the interval tree and its types don't seem to be exposed. Is there any reason for that, or would that be a reasonable feature request?

**Comment by jaredLunde** [comment]
This is a completely reasonable request and an oversight on my part. You’re doing exactly what I want people to do when the positioning algorithm doesn’t satisfy a use case.

**Comment by bnjmnt4n** [comment]
Thanks for the quick response! Let me know if you’d like a PR for this.

**Comment by jaredLunde** [comment]
Go for it! I’m AFK right now but I’ll be back in an hour. Can merge/release your PR then.
