### ISSUE TITLE
Mutating state during render

### ISSUE THREAD

**Issue by bnjmnt4n** [jaredLunde/masonic#61]
This is more of a question than a feature request.

I noticed that in use-positioner.ts (https://github.com/jaredLunde/masonic/blob/master/src/use-positioner.ts#L53-L71), state (the positioner) is mutated during the render function and not in any effect. I understand that it is important for the positioner to be updated before laying out the new items, but wondered if there were any potential drawbacks to that approach, especially with React's concurrent mode not recommending such mutations.

**Comment by jaredLunde** [comment]
it has been tested with concurrent mode and is concurrent mode-safe

**Comment by jaredLunde** [comment]
Closing this, because it does seem to work. That said, I do understand the issue and I will use a more palatable solution in the future.
