### ISSUE TITLE
Weird black border around <Masonry> when clicked

### ISSUE THREAD

**Issue by tchu1997** [jaredLunde/masonic#62]
**Describe the bug**
Whenever I click on the masonry component, a black border is shown around the component.
All the demos in the documentation contain this border as well.
I tried to add border: none and outline: none for .masonic but nothing happened.
How do I remove the border?

**To Reproduce**
1. Supply the Masonry component with any array of items
2. Black border is shown when the masonry wall is clicked
3. When click away, black border disappears. 

**Expected behavior**
A solid 1px black border around the masonry wall.

**Screenshots**
My website:
![image](https://user-images.githubusercontent.com/54428906/104709700-16c50c00-56d4-11eb-9ed9-a61dffdb56b3.png)
Demo:
![image](https://user-images.githubusercontent.com/54428906/104710423-eaf65600-56d4-11eb-9e92-cb6b3edae67a.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome, Edge
- Version: latest version

**Smartphone (please complete the following information):**

Not yet tested on smartphone

**Comment by picoLizard** [comment]
Hi, I have the same problem in my app with the black border.

The following (brute force) removes it for me; assume some style somewhere is adding the outline (although I couldn't find it inspecting the styles in chrome).

*:focus {
        outline: none;
      }

**Comment by jaredLunde** [comment]
The container is focusable because it is screen reader interactive. You can customize focus styles by adding a container style or container class.
