### ISSUE TITLE
There is always some space at the bottom

### ISSUE THREAD

**Issue by dnish** [jaredLunde/masonic#66]
Hey,
thank you very much for creating this plugin. I got everything to work but facing a little issue when using images. There is always a little "margin/space" on the bottom of the items. It seems like that the griditem div is always a little bit higher than the image within it. Is there any way to remove that space? I've already tried to add <code>height: fit-content;</code> to the griditem div, but that didn't work. My only dirty workaround is currently using <code>transform: scaleY(1.05)</code> on the image to zoom it.

<img width="1768" alt="Bildschirmfoto 2021-02-21 um 15 32 49" src="https://user-images.githubusercontent.com/7636313/108628249-1d286f80-745a-11eb-9da4-461bb059fab2.png">

**Comment by jaredLunde** [comment]
Can you post a repro to CodeSandbox? I have not experienced this myself.

**Comment by dnish** [comment]
I could fix the problem by adding the height of the image to the element :-)
