### ISSUE TITLE
loadMoreItems() fires multiple times

### ISSUE THREAD

**Issue by theochampion** [jaredLunde/masonic#69]
Hi there,

Loving the library <3

I'm trying to use the useInfinitLoader hook to call my API and fetch more content but i'm running into what seems to be an odd behavior.
If i set up `useInfinitLoader` like so:

```javascript
  const maybeLoadMore = useInfiniteLoader(
    async (startIndex, stopIndex, currentItems) => {
      console.log("loadMoreItems called", startIndex, stopIndex);
      await new Promise((res, rej) => setTimeout(res, 10000));
      const nextItems = await getFakeItemsPromise(startIndex, stopIndex);
      setItems((current) => [...current, ...nextItems]);
    },
    {
      isItemLoaded: (index, items) => !!items[index],
      minimumBatchSize: 32,
      threshold: 15
    }
  );
```

And scroll in my list, `loadMoreItems` is called multiples times (one for every item above the threshold) thus multiple similar call are made the my API.  See the sandbox below

https://codesandbox.io/s/useinfiniteloader-example-forked-vmmn0?file=/src/index.js

Is this the expected behavior? To me, it would make more sense to have `loadMoreItems` called only once when rendering an item above the threshold.

Cheers !

**Comment by jaredLunde** [comment]
Docs literally say this happens

**Comment by greenlihui** [comment]
> Docs literally say this happens

Similar thing happens here, `loadMoreItems` were called multiple times with same `startIndex` and `stopIndex`, which resulted that my grid showing duplicate items, do u have any plans to fix this?

 Thanks for providing the library : )

<img width="1536" alt="Screen Shot 2021-03-25 at 22 47 22" src="https://user-images.githubusercontent.com/22424939/112775403-64180f00-906f-11eb-800d-19cefef42289.png">

**Comment by jaredLunde** [comment]
it. is. not. a. bug.

memoize.

**Comment by chucksellick** [comment]
This is the same issue I have reported ... clearly there is some common misunderstanding of the functionality here, can you provide some more explanation of exactly what to memoize and how this should work? I am happy to submit a PR to improve docs if I can understand how this hook is supposed to be used.

**Comment by jaredLunde** [comment]
Memoize the arguments safe for you to memoize. There are only three. Pretty simple.

**Comment by jaredLunde** [comment]
This honestly is not complicated and it behaves this way for good reason. Apparently people get upset when they have to put in the most basic amount of effort or thought. Design the callback in a way that suits your case ffs.

**Comment by theochampion** [comment]
@jaredLunde I don't think any of us have a problem with the design decision of this.

The root issue seems to be the code you used to illustrate this functionality.

(taken from the README.md)
```javascript
import * as React from 'react'
import {Masonry, useInfiniteLoader} from 'masonic'

const InfiniteMasonry = (props) => {
  const [items, setItems] = useState([
    /* initial items */
  ])
  const fetchMoreItems = async (startIndex, stopIndex, currentItems) => {
    const nextItems = await fetch(
      `/api/get-more?after=${startIndex}&limit=${startIndex + stopIndex}`
    )

    setItems((current) => [...current, ...nextItems])
  }
  const maybeLoadMore = useInfiniteLoader(fetchMoreItems, {
    isItemLoaded: (index, items) => !!items[index],
  })

  return <Masonry {...props} items={items} onRender={maybeLoadMore} />
}
```

This code would yield a huge amount of unnecessary API calls, thus leading to confusion.

**Comment by jaredLunde** [comment]
Happy to accept a PR that updates the example. The fact is, there's no singular way to handle every case. Sometimes you'll need useCallback and memoize, sometimes just memoize, sometimes it doesn't matter. The docs are pretty good at covering the most basic cases and I don't consider it my imperative to teach people how to use the library beyond what I've already spent literal days writing. This is something I've provided for free and it's the user's job to learn it unless I make a paid course. So yeah, it's frustrating. But I do hear you and like I said I'm happy to accept a pull from anyone who can provide a concise example.

**Comment by chucksellick** [comment]
> This honestly is not complicated and it behaves this way for good reason. Apparently people get upset when they have to put in the most basic amount of effort or thought. Design the callback in a way that suits your case ffs.

Thank you, I eventually got the infinite scroll working really nicely after a day or so of tweaking and testing various strategies for handling this, thanks also to the suggestions in this thread. And @jaredLunde thank you so much for your work on this library, now I have it running it's impressively performant and has truly wowed people who've seen the beta.

But I was not upset at having to put in some work, I just came up against a bit of a roadblock in the implementation and documentation, surely you have experienced a similar thing using other people's libraries? Especially when you are working across an entire architecture to put together a solution with many different technologies, what seems like only a little gap to you became a massive pain point for me. But yes, after I considered things further and tinkered a bit I was able to fill it out.

The library professes to be "batteries included" so don't get angry when people are just wondering if they have misplaced a battery :)

I am thinking it might be possible to include something that handles this in a very default way but is swappable for a more complex strategy, this default implementation would be a simple state container that manages the list of items and dedupes the paging calls. Would a PR like this be of interest?

**Comment by sebyx07** [comment]
I use this pattern:

```js
import {feedBackError} from '../../events/feedback';
import {fetchGalleryElements} from './store';
import {useInfiniteLoader} from 'masonic';
import {useRef} from 'react';

let loadedGalleryItemsIndexes = [];
export function resetLoadedGalleryItemsIndexes() {
  loadedGalleryItemsIndexes = [];
}

export function useGalleryInfiniteLoad({state, galleryElementsCount, imageAlbumId}) {
  const fetchMoreItems = async (startIndex, endIndex) => {
// the trick start
    const newIndex = {endIndex, startIndex};
    const existing = loadedGalleryItemsIndexes.find((el) => {
      return el.startIndex === newIndex.startIndex && el.endIndex === newIndex.endIndex;
    });
    if (existing) return; 
    loadedGalleryItemsIndexes.push(newIndex);
 // trick end
    try {
      const {data: {galleryElements}} = await fetchGalleryElements(imageAlbumId, startIndex, endIndex);
      state.merge((s) => {
        return {
          galleryElements: [...s.galleryElements, ...galleryElements],
        };
      });
    } catch (e) {
      feedBackError('unable to fetch images');
    }
  };
  const maybeLoadMore = useRef(useInfiniteLoader(fetchMoreItems, {
    isItemLoaded: (index, items) => !!items[index],
    totalItems: galleryElementsCount + 1,
  }));

  return {maybeLoadMore};
}

```

and inside the list

```js
  const {maybeLoadMore} = useGalleryInfiniteLoad({galleryElementsCount, imageAlbumId, state});
    <MasonryScroller onRender={maybeLoadMore.current} />
```

**Comment by sebyx07** [comment]
here is the full example:
https://github.com/personal-social-media/personal-social-media/blob/master/app/javascript/components/image-album/gallery-list.jsx

https://github.com/personal-social-media/personal-social-media/blob/master/app/javascript/components/image-album/use-gallery-infinite-load.js
