### ISSUE TITLE
First "page" load yield hidden cells

### ISSUE THREAD

**Issue by theochampion** [jaredLunde/masonic#70]
Hi there,

I'm facing a weird issue where, sometimes (one third of the times on avg) when the grid is first loaded on my page, cells are rendered as hidden:

```css
    width: 348px;
    z-index: -1000;
    visibility: hidden;
    position: absolute;
    writing-mode: horizontal-tb;
```

And they remain this way until I either scroll (down) or resize the window.

I was unfortunately not able to reproduce the bug in a sandbox env but my setup is pretty much identical to [this recipe](https://codesandbox.io/s/masonic-w-react-router-and-advanced-config-example-8em42?file=/src/index.js)

What kind of external factor could cause this behavior? Is there anything that I should look into in particular?

I'm using masonic `3.4.1`

Cheers!

**Comment by jaredLunde** [comment]
Which React version are you using? Also are you using concurrent mode, strict mode, etc?

**Comment by theochampion** [comment]
@jaredLunde I'm using `react: 17.0.0` and `react-dom: 17.0.0` in Strict Mode

**Comment by bnjmnt4n** [comment]
I've actually encountered this before, and was going to open an issue for this, but it slipped my mind. Seems like it might have to do with `useSize`. Here's my local workaround:

```
  const { height } = useSize(scrollContainerRef);
  useEffect(() => {
    if (height === 0) {
      window.dispatchEvent(new Event("resize"));
    }
  }, [height]);
```

**Comment by theochampion** [comment]
@bnjmnt4n In my code I'm using the whole window as the view so I use the `useWindowSize` hook instead which always seems to report the height correctly:

```javascript
const [windowWidth, windowHeight] = useWindowSize();
```

If I add your code under, the dispatched event seem to "fix" the issue. This is quite weird
