### ISSUE TITLE
useInfiniteLoader keeps requesting same indicies over and over

### ISSUE THREAD

**Issue by chucksellick** [jaredLunde/masonic#73]
**Describe the bug**
I am trying to implement infinite scroll against a graphql search API. I have followed the example on codesandbox, but since it is faking an API call it is not a real-world example, and it is very unclear exactly how this translates to real API scenarios.
What happens when the hook tries to load more items is it fires my callback multiple times with the exact same start/stop indexes, and if I return the results every time I end up with items repeated over and over again.
So I added a lookup so that I was able to omit results from the list if they have already been used, this caused the thing to go into overdrive and start triggering the callback 1000s of times and then lock up the browser.

Perhaps I am missing something and there is somewhere a more complete example of the infinite scroll hook in real world use?

**To Reproduce**
Try to implement an infinite scroll where pages are loaded asynchronously from a slowish API (which could take a few seconds).

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: latest

**Comment by theochampion** [comment]
@chucksellick have a look at this https://github.com/jaredLunde/masonic/issues/69
