### ISSUE TITLE
Unable to render items when scrolling down.

### ISSUE THREAD

**Issue by jruts** [jaredLunde/masonic#75]
**Describe the bug**
I have a _very_ simple use case where I need to render X amount of cards.
Whenever I scroll down and I scroll past the over scan, not a single item is rendered anymore.
The scrollbar indicates that there are a lot more items, but none of them get actually rendered

**To Reproduce**
following code will render 1000 items with similar data to mine:
```js
const items =  Array.from(Array(1000), (item, index) => ({
    id: index,
    name: "just a product name",
    image: "just a url",
    shelf: "some shelf name",
    retailer: "some retailer name"
  }))
);
```

this is my react component using masonic:
```js
import React from "react";
import { Masonry } from "masonic";

// components
import ProductCard from "./ProductCard";

const ProductMasonry = ({ products = [] }) => {
  return (
    <div style={{ boxSizing: "border-box" }}>
      {products.length > 0 && (
        <Masonry
          style={{ outline: "none" }}
          items={products}
          columnGutter={8}
          columnWidth={250}
          overscanBy={1}
          render={ProductCard}
        />
      )}
    </div>
  );
};

export default ProductMasonry;
```

And this is the actual card component:
```js
import {
  Box,
  Card,
  CardContent,
  CardHeader,
  CardMedia,
  Checkbox,
  Chip,
  makeStyles,
  Typography,
} from "@material-ui/core";
import React from "react";

const useStyles = makeStyles((theme) => ({
  root: {
    minHeight: "400px",
    "&:hover": {
      backgroundColor: "#efefef",
    },
  },
  media: {
    minHeight: "135px",
    maxHeight: "135x",
    backgroundSize: "contain",
  },
  chip: {
    borderRadius: theme.spacing(0.5),
  },
  content: {
    height: "217px",
    display: "flex",
  },
  header: {
    padding: theme.spacing(1),
  },
  checkbox: {
    padding: 0,
    paddingRight: theme.spacing(1),
  },
}));

const Header = (data, classes) => {
  return (
    <Box display="flex">
      <Box flexGrow={1} display="flex" alignItems="center">
        <Checkbox className={classes.checkbox} />
        <Typography variant="caption">{data.retailer}</Typography>
      </Box>
    </Box>
  );
};

const ProductCard = ({ data }) => {
  const classes = useStyles();
  return (
    <Card className={classes.root} variant="outlined">
      <CardHeader className={classes.header} title={Header(data, classes)} />
      <CardMedia image={data.image} className={classes.media} />
      <CardContent className={classes.content}>
        <Box display="flex" flexDirection="column">
          <Box flexGrow={1}>
            <Typography variant="subtitle2">{data.name}</Typography>
          </Box>
          <Box>
            {data.shelf && (
              <Chip className={classes.chip} size="small" label={data.shelf} />
            )}
            <br />
          
          </Box>
        </Box>
      </CardContent>
    </Card>
  );
};

export default ProductCard;

```

**Expected behavior**
I expect to see the cards  when I scroll down

**Screenshots**
![image](https://user-images.githubusercontent.com/7126237/114678815-e78e5d00-9d0b-11eb-8009-ffe54191c563.png)

the last item you see there is item 12, and that is where the rendering stops. I can scroll all the way down to the last item, but nothing is rendered. Looking at the scrollbar and the ability to scroll all the way down it knows however there should be 100 cards (which is the dataset size used in the screenshot)

**Additional context**
I have looked at the basic Masonic example on codesanbox and I am hitting my head against the wall as to why this is happening.

**Comment by jruts** [comment]
Just want to clarify that it is not triggering anything when the overscan is reached. I tried to attach an inifniteLoader to see of that gets triggered, but that is not the case either.

**Comment by jruts** [comment]
Investigating further it seems like the scroll event is not triggered. The scrollbar is on the browser window, but it does not seem to be attacked to the scroll event of Masonic that should trigger the renders.

Am I missing something here?

**Comment by Shinchan3102** [comment]
Hey @breakinferno  and @jruts  did you get any solution for this i am stucked with the same issue
