### ISSUE TITLE
Broken on iOS Safari

### ISSUE THREAD

**Issue by anduong96** [jaredLunde/masonic#8]
![Screen Shot 2020-04-24 at 9 45 02 PM](https://user-images.githubusercontent.com/13195989/80272960-16d33680-8683-11ea-8812-24bbd83cb42a.png)

Not sure why but, it works on every browser except iOS Safari.

sample code
`
            <Masonry
              className={classCtx('products-list')}
              columnGutter={5}
              columnCount={columnCount}
              items={products}
              itemKey={(item) => item?._id || uniqueId()}
              render={({ data }) => {
                return (
                  <ProductCard
                    {...data}
                  />
                )
              }}
            />
`

**Comment by jaredLunde** [comment]
I'm not sure what's causing your issue, but it's not specific to this library. The code sandbox example works fine on my iPhone.

**Comment by jaredLunde** [comment]
You should try it without the render component as a closure, though. That's not really the intended use and it could cause performance problems.
```jsx harmony

const Main = () => (
   <Masonry className={classCtx('products-list')} columnGutter={5} columnCount={columnCount} items={products} itemKey={(item) => item?._id || uniqueId()} render={RenderComponent} />
)

const RenderComponent = ({ data }) => { return ( <ProductCard {...data} /> ) }
```
